name: darto
description: Darto is a microframework inspired by Express ify for building web applications in Dart.
version: 0.0.31
homepage: https://github.com/evandersondev/darto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.1
  mime: ^2.0.0
  ansicolor: ^2.0.3
  http: ^1.3.0
  http_parser: ^4.1.2
  web_socket_channel: ^3.0.3
  mailer: ^6.4.1
  mustache_template: ^2.0.0
  intl: ^0.20.2
  darto_types:
    git:
      url: https://github.com/evandersondev/darto_types
      ref: main

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  lints: any
